const config = require('../package.json');

function generateMarkdown(data) {
  
  return `

# ${data.projectName} v${config.version}

${data.projectDescription}

## Table of Contents
- [Installation](#installation)
- [Usage](#usage)
- [Running Tests](#testing)
- [Repository Info](#repository)
- [Contribution](#contribution)
- [License Info](#license)
- [Questions](#questions)

![${data.projectName}](https://img.shields.io/badge/License-${data.projectLicense}-blue)
![${data.projectName}](https://img.shields.io/badge/ReadMeGenerator-${config.version}-green)
## Installation
<code>${data.runDependencies}</code>

## Usage
<code>${data.projectUsage}</code>

## Testing
<code>${data.runTest}</code>

## Repository
<code>git clone ${data.projectRepository}</code>

## Contribution
${data.projectContribution}

## License
${data.projectLicense}

## Questions
GH :: ${data.userName} - Email :: ${data.emailAddress}

![${data.userName} Profile Photo](https://github.com/${data.userName}.png)

> This README.md was generated by ${data.projectName}
  `;
}

module.exports = generateMarkdown;
