const config = require('../package.json');

function generateMarkdown(data) {
  
  return `

# ${data.projectName} v${config.version}

${data.projectDescription}

![${data.projectName}](https://img.shields.io/github/license/${data.userName}/${data.projectName})
![${data.projectName}](https://img.shields.io/badge/ReadMeGenerator-${config.version}-green)
## Installation : 
<code>${data.runDependencies}</code>

## Usage : 
<code>${data.projectUsage}</code>

## Running Tests :
<code>${data.runTest}</code>

## Repository Info :
<code>git clone ${data.projectRepository}</code>

## Contribution :
${data.projectContribution}

## License Type :
${data.projectLicense}

GH :: ${data.userName} - Email :: ${data.emailAddress}
![${data.userName} Profile Photo](https://github.com/${data.userName}.png)

> This README.md was generated by ${data.projectName}
  `;
}

module.exports = generateMarkdown;
