const config = require('../package.json');

  // Example Object this function is expecting. 
  // {
  //   login: 'nathan-gianelli',
  //   id: 59578229,
  //   node_id: 'MDQ6VXNlcjU5NTc4MjI5',
  //   avatar_url: 'https://avatars2.githubusercontent.com/u/59578229?v=4',
  //   gravatar_id: '',
  //   url: 'https://api.github.com/users/nathan-gianelli',
  //   html_url: 'https://github.com/nathan-gianelli',
  //   followers_url: 'https://api.github.com/users/nathan-gianelli/followers',
  //   following_url: 'https://api.github.com/users/nathan-gianelli/following{/other_user}',
  //   gists_url: 'https://api.github.com/users/nathan-gianelli/gists{/gist_id}',
  //   starred_url: 'https://api.github.com/users/nathan-gianelli/starred{/owner}{/repo}',
  //   subscriptions_url: 'https://api.github.com/users/nathan-gianelli/subscriptions',
  //   organizations_url: 'https://api.github.com/users/nathan-gianelli/orgs',
  //   repos_url: 'https://api.github.com/users/nathan-gianelli/repos',
  //   events_url: 'https://api.github.com/users/nathan-gianelli/events{/privacy}',
  //   received_events_url: 'https://api.github.com/users/nathan-gianelli/received_events',
  //   type: 'User',
  //   site_admin: false,
  //   name: null,
  //   company: null,
  //   blog: '',
  //   location: null,
  //   email: null, // Not sure why this comes back as null. 
  //   hireable: null,
  //   bio: null,
  //   public_repos: 13,
  //   public_gists: 0,
  //   followers: 0,
  //   following: 0,
  //   created_at: '2020-01-06T18:51:18Z',
  //   updated_at: '2020-02-25T20:29:00Z',
  //   userName: 'nathan-gianelli',
  //   emailAddress: 'nathan.gianelli98@gmail.com',
  //   projectName: 'read-me-generator',
  //   projectDescription: 'barf',
  //   projectLicense: 'dfghjkl',
  //   projectUsage: 'fghjkl',
  //   runDependencies: 'fghjkl;',
  //   runTest: 'dfghjkl',
  //   projectRepository: 'asdfghjkl;',
  //   projectContribution: 'fghjk'
  // }
function generateMarkdown(data) {
  
  // Debug
  // console.log(data);

  return `

# ${data.projectName} v${config.version}

${data.projectDescription}

## Table of Contents
- [Installation](#installation)
- [Usage](#usage)
- [Running Tests](#testing)
- [Repository Info](#repository)
- [Contribution](#contribution)
- [License Info](#license)
- [Questions](#questions)

![${data.projectName}](https://img.shields.io/badge/License-${data.projectLicense}-blue)
![${data.projectName}](https://img.shields.io/badge/ReadMeGenerator-${config.version}-green)
## Installation
<code>${data.runDependencies}</code>

## Usage
<code>${data.projectUsage}</code>

## Testing
<code>${data.runTest}</code>

## Repository
<code>git clone ${data.projectRepository}</code>

## Contribution
${data.projectContribution}

## License
${data.projectLicense}

## Questions
Github :: ${data.userName} - Email :: ${data.emailAddress}

![${data.userName} Profile Photo](${data.avatar_url})

> This README.md was generated by ${data.projectName}
  `;
}

module.exports = generateMarkdown;
